dbt_chicago:
  target: dev
  outputs:
    dev:
      type:      snowflake
      account:   [your_account]
      user:      [EMAIL_ADDRESS]
      password:  [PASSWORD]
      role:      ACCOUNTADMIN
      database:  TAXI_DB
      warehouse: TAXI_WH
      schema:    STAGING
      threads:   4